#!/usr/bin/env sh

cd ../build

aws --endpoint-url http://localhost:4566 iam create-role \
--role-name lambda-cpp-demo \
--assume-role-policy-document file://trust-policy.json

aws --endpoint-url http://localhost:4566 lambda create-function \
--function-name hello-world \
--role arn:aws:iam::000000000000:role/lambda-cpp-demo \
--runtime provided \
--timeout 15 \
--memory-size 128 \
--handler hello \
--zip-file fileb://hello.zip
