#!/usr/bin/env sh

mkdir -p build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=~/out -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
make && make aws-lambda-package-hello
echo "{" > trust-policy.json
echo "  \"Version\": \"2012-10-17\"," >> trust-policy.json
echo "  \"Statement\": [" >> trust-policy.json
echo "    {" >> trust-policy.json
echo "      \"Effect\": \"Allow\"," >> trust-policy.json
echo "      \"Principal\": {" >> trust-policy.json
echo "        \"Service\": [\"lambda.amazonaws.com\"]" >> trust-policy.json
echo "      }," >> trust-policy.json
echo "      \"Action\": \"sts:AssumeRole\"" >> trust-policy.json
echo "    }" >> trust-policy.json
echo "  ]" >> trust-policy.json
echo "}" >> trust-policy.json
