#!/usr/bin/env sh

cd ~

sudo dnf install -y cmake libcurl-devel python3-devel

curl https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip -o awscliv2.zip
unzip awscliv2.zip
sudo ./aws/install
rm awscliv2.zip
rm -r aws

sudo pip3 install localstack

curl -L https://releases.hashicorp.com/terraform/1.0.4/terraform_1.0.4_linux_arm64.zip -o terraform.zip
unzip terraform.zip
sudo mv terraform /usr/bin
rm terraform.zip

aws configure